/**
 * Product data for the e-commerce store
 * This simulates a database of products
 */

const products = [
  {
    id: 1,
    name: "Laptop Stand",
    category: "accessories",
    price: 49.99,
    image: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=800&q=85",
    description:
      "Adjustable aluminum laptop stand for better ergonomics and cooling. Compatible with all laptop sizes.",
    specifications: { Material: "Aluminum", Compatibility: "Universal laptops", Feature: "Adjustable height" },
    inStock: true,
    rating: 4.5,
  },
  {
    id: 2,
    name: "Wireless Mouse",
    category: "accessories",
    price: 29.99,
    image: "https://images.unsplash.com/photo-1527814050087-3793815479db?auto=format&fit=crop&w=800&q=85",
    description: "Ergonomic wireless mouse with 2.4GHz connection. 18-month battery life.",
    specifications: { Connection: "2.4GHz wireless", Battery: "18-month battery life", Tracking: "Optical" },
    inStock: true,
    rating: 4.3,
  },
  {
    id: 3,
    name: "USB-C Hub",
    category: "electronics",
    price: 79.99,
    image: "https://images.unsplash.com/photo-1625842268584-8f3296236761?auto=format&fit=crop&w=800&q=85",
    description:
      "7-in-1 USB-C hub with HDMI, USB 3.0 ports, SD card reader, and power delivery up to 100W.",
    specifications: { Ports: "7-in-1", Output: "4K HDMI", Power: "Up to 100W PD" },
    inStock: true,
    rating: 4.6,
  },
  {
    id: 4,
    name: "Mechanical Keyboard",
    category: "accessories",
    price: 129.99,
    image: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=800&q=85",
    description:
      "RGB mechanical keyboard with Cherry MX switches. Programmable keys and aluminum frame.",
    specifications: { Switches: "Cherry MX", Backlight: "RGB", Layout: "Full-size" },
    inStock: true,
    rating: 4.7,
  },
  {
    id: 5,
    name: "4K Monitor",
    category: "electronics",
    price: 399.99,
    image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=800&q=85",
    description: "27-inch 4K UHD monitor with 99% sRGB color accuracy. Ideal for content creation.",
    specifications: { Size: "27 inches", Resolution: "3840 x 2160", Color: "99% sRGB" },
    inStock: true,
    rating: 4.4,
  },
  {
    id: 6,
    name: "Webcam",
    category: "electronics",
    price: 89.99,
    image: "https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04?auto=format&fit=crop&w=800&q=85",
    description: "1080p HD webcam with auto-focus and built-in stereo microphone.",
    specifications: { Resolution: "1080p Full HD", Focus: "Auto-focus", Audio: "Stereo microphone" },
    inStock: true,
    rating: 4.2,
  },
  {
    id: 7,
    name: "Monitor Arm",
    category: "accessories",
    price: 59.99,
    image: "https://images.unsplash.com/photo-1558655146-d09347e92766?auto=format&fit=crop&w=800&q=85",
    description: "Gas spring monitor arm for single displays. VESA compatible, supports up to 17 lbs.",
    specifications: { Mount: "VESA compatible", Capacity: "17 lbs", Movement: "Gas spring" },
    inStock: true,
    rating: 4.5,
  },
  {
    id: 8,
    name: "Desk Lamp",
    category: "accessories",
    price: 39.99,
    image: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=800&q=85",
    description:
      "LED desk lamp with adjustable brightness and color temperature. Touch control and USB charging port.",
    specifications: { Control: "Touch control", Light: "Adjustable temperature", Extra: "USB charging port" },
    inStock: true,
    rating: 4.4,
  },
  {
    id: 9,
    name: "Wireless Charger",
    category: "electronics",
    price: 24.99,
    image: "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=800&q=85",
    description: "Fast wireless charging pad. Compatible with Qi-enabled devices.",
    specifications: { Standard: "Qi wireless", Design: "Non-slip pad", Compatibility: "Qi-enabled devices" },
    inStock: true,
    rating: 4.1,
  },
  {
    id: 10,
    name: "Portable SSD",
    category: "electronics",
    price: 149.99,
    image: "https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?auto=format&fit=crop&w=800&q=85",
    description: "1TB portable SSD with USB 3.1. Compact and durable design.",
    specifications: { Capacity: "1TB", Interface: "USB 3.1", Design: "Compact and durable" },
    inStock: true,
    rating: 4.6,
  },
  {
    id: 11,
    name: "Desk Organizer",
    category: "accessories",
    price: 19.99,
    image: "https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=800&q=85",
    description: "Bamboo desk organizer with multiple compartments for office supplies.",
    specifications: { Material: "Bamboo", Compartments: "Multiple", Use: "Office supplies" },
    inStock: true,
    rating: 4.3,
  },
  {
    id: 12,
    name: "Phone Stand",
    category: "accessories",
    price: 14.99,
    image: "https://images.unsplash.com/photo-1586953208448-b95a79798f07?auto=format&fit=crop&w=800&q=85",
    description: "Adjustable phone stand compatible with all smartphone sizes.",
    specifications: { Material: "Durable alloy", Adjustment: "Adjustable angle", Compatibility: "All smartphones" },
    inStock: true,
    rating: 4.2,
  },
];

module.exports = products;
